### PR TITLE
Post Contacts Controller

### LINKED ISSUE #489: 'Manage Contact Page' admin page not saving changes to database
#### Description

`Manage Contact Page` admin page not saving changes for user order, visibility -- returning `Cannot POST /admin/contact` error.

#### To Reproduce

1. Log in to BH as an admin user.
2. Select `Manage Contact Page.`
3. Make any changes to contact display order or visibiltiy. 
4. Select 'Submit.'
5. Error page is returned and submission not saved to database.

### PR DESCRIPTION
**Pull request by pltaylor**
This is an attempt to fix [this issue](https://github.com/brigadehub/brigadehub/issues/489)

- [x] Add controller for Post Contacts
- [x]  Ensure page posts to correct controller
- [x]  Ensure showcontact is written to the db
- [x] Ensure Contact Rank is written to the db

It currently appears that showcontact is not being passed back in the request model, I'm not sure why.

Also I added the capability to lint the project using 'make lint', please check the settings to make sure they are sane.

### CODE REVIEW

File: controllers/contact/postContact.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  endpoint: '/contact',
+  authenticated: true,
+  roles: ['core', 'superAdmin'],
+  scopes: ['user:email', 'repo', 'admin:org', 'admin:repo_hook', 'admin:org_hook'],
+  middleware: [],
+  controller: postContactsManage
+}
+
+function postContactsManage (req, res) {
+  var Contact = req.models.Users
```
Comment (therebelrobot) [inline controllers/contact/postContact.js]: We generally want model references to be the name of the file, changing it to `Contact` makes me think we added a `Contact` collection in mongo and are referencing it here.

`Users` would be ideal in this situation.

File: controllers/contact/postContact.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+  var mongooseQuery = {}
+
+  Contact.find(mongooseQuery, function (err, contacts) {
```
Comment (therebelrobot) [inline controllers/contact/postContact.js]: same for `contacts`, probably want it to be `users`

File: controllers/contact/postContact.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+      else{
+        contact.profile.showcontact = true
+      }
+      contact.profile.contactpagerank = contactInfo.contactrank
+      contact.save(function (err) {
+        if (err) throw err
+      })
+    })
+  })
+  req.flash('success', {msg: 'Success! You updated contacts.'})
```
Comment (therebelrobot) [inline controllers/contact/postContact.js]: this is being done out of band of the actual save, so it's not indicative of the action being successful. Should be moved to between lines 28-29, and the throw err there should be refactored to flash and redirect.

File: package.json [hunk 4]
```diff
@@ -4,6 +4,7 @@
   "description": "",
   "main": "index.js",
   "scripts": {
+    "standard": "standard",
```
Comment (therebelrobot) [inline package.json:7]: we generally want unrelated changes to be PR'd separately, so they can go in without being blocked by other concerns.

It's ok here for now, but in the future let's move to more atomic pull requests.

**Review by therebelrobot — CHANGES_REQUESTED** [review]
Excellent work! A couple of fixes needed:

File: package.json (hunk 4 above)
Comment (pltaylor) [reply package.json:7]: Understood and agree 100%.

File: controllers/contact/postContact.js [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+        user.profile.showcontact = true
+      }
+      user.profile.contactpagerank = userInfo.contactrank
+      user.save(function (err) {
+        if (err) throw err
+        req.flash('success', {msg: 'Success! You updated contacts.'})
+      })
+    })
+  })
+  return res.redirect('contact/edit')
```
Comment (therebelrobot) [inline controllers/contact/postContact.js]: this redirect needs to be moved to directly after the success flash above

File: controllers/contact/postContact.js [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+    users.forEach(function (user) {
+      var userInfo = req.body[user.username]
+      if (!userInfo.showcontact) {
+        user.profile.showcontact = false
+      } else {
+        user.profile.showcontact = true
+      }
+      user.profile.contactpagerank = userInfo.contactrank
+      user.save(function (err) {
+        if (err) throw err
```
Comment (therebelrobot) [inline controllers/contact/postContact.js]: this `throw err` will kill the server. Expand out the if block and add a new `req.flash('errors', ...)` with a `return res.redirect` to where it should go upon failure.

**Review by therebelrobot — CHANGES_REQUESTED** [review]

File: controllers/contact/postContact.js (hunk 6 above)
Comment (pltaylor) [reply controllers/contact/postContact.js]: I'm honestly not sure where it should go if it has errors.  Do we have an error page?

**Review by therebelrobot — APPROVED** [review]
Looks great!
